import React, { useState } from 'react';
import '../css/HelpAndFAQPage.css';

const HelpAndFAQPage = () => {
  const [openIndex, setOpenIndex] = useState(null);
  const [searchQuery, setSearchQuery] = useState('');

  const faqCategories = [
    {
      id: 'getting-started',
      title: 'Getting Started',
      icon: '',
      questions: [
        {
          q: 'How do I create my first bot?',
          a: 'Creating a bot is easy! Go to Bot Setup, click "New Bot", give it a name, upload your documents, and start chatting. No coding required!',
        },
        {
          q: 'What file types can I upload?',
          a: 'You can upload PDFs, Word documents (.doc, .docx), text files (.txt), and Markdown files (.md). The system will automatically extract and process the content.',
        },
        {
          q: 'How does the Code to Document feature work?',
          a: 'Simply upload your code files or paste code, and our AI will generate professional documentation. You can export it as a PDF or view it in the preview panel.',
        },
        {
          q: 'Do I need to install anything?',
          a: 'No installation needed! Everything runs in your browser. Just make sure LM Studio is running on your machine if you\'re using local AI models.',
        },
      ],
    },
    {
      id: 'bot-setup',
      title: 'Bot Setup',
      icon: '',
      questions: [
        {
          q: 'How many documents can I upload per bot?',
          a: 'You can upload multiple documents to each bot. There\'s no strict limit, but we recommend keeping it under 50 documents for optimal performance.',
        },
        {
          q: 'What is RAG and how does it work?',
          a: 'RAG (Retrieval Augmented Generation) allows your bot to answer questions based on your uploaded documents. The system searches through your documents to find relevant information and uses it to generate accurate answers.',
        },
        {
          q: 'Can I customize my bot\'s personality?',
          a: 'Yes! In the bot configuration, you can set a custom system prompt that defines how your bot behaves and responds. We also provide preset templates to get you started.',
        },
        {
          q: 'How long does it take to vectorize documents?',
          a: 'Vectorization typically takes a few seconds to a minute depending on document size. You\'ll see a progress indicator during the process.',
        },
        {
          q: 'Can I edit my bot after creating it?',
          a: 'Absolutely! You can update your bot\'s name, description, system prompt, and settings at any time. Just select the bot and click "Save Changes".',
        },
      ],
    },
    {
      id: 'code-to-doc',
      title: 'Code to Document',
      icon: '',
      questions: [
        {
          q: 'Which programming languages are supported?',
          a: 'We support all major programming languages including Python, JavaScript, TypeScript, Java, C++, Go, Rust, and more. The AI understands code structure regardless of language.',
        },
        {
          q: 'Can I generate documentation for multiple files at once?',
          a: 'Yes! You can upload up to 5 files at once. The system will combine them and generate comprehensive documentation covering all your code.',
        },
        {
          q: 'How accurate is the generated documentation?',
          a: 'The documentation is generated by advanced AI models and is highly accurate. However, we recommend reviewing and editing the output to ensure it meets your specific needs.',
        },
        {
          q: 'Can I export the documentation?',
          a: 'Yes! Once generated, you can download the documentation as a PDF file. The PDF includes proper formatting, code snippets, and all sections.',
        },
        {
          q: 'What if my code is very large?',
          a: 'For very large codebases, we recommend breaking it into smaller sections or focusing on specific modules. The system handles files up to a certain size limit for optimal performance.',
        },
      ],
    },
    {
      id: 'troubleshooting',
      title: 'Troubleshooting',
      icon: '',
      questions: [
        {
          q: 'My bot isn\'t responding correctly. What should I do?',
          a: 'Try these steps: 1) Check if your documents were successfully uploaded and vectorized, 2) Review your system prompt, 3) Try rephrasing your question, 4) Make sure LM Studio is running and connected.',
        },
        {
          q: 'The API shows as offline. How do I fix this?',
          a: 'Ensure LM Studio is running on your machine and the API URL in settings is correct. Check that the port matches your LM Studio configuration (default is 1234).',
        },
        {
          q: 'Documents are not uploading. What\'s wrong?',
          a: 'Check that: 1) File size is within limits, 2) File type is supported, 3) Your internet connection is stable, 4) The backend server is running. Try refreshing the page if issues persist.',
        },
        {
          q: 'How do I reset my bot?',
          a: 'You can delete a bot and create a new one, or simply update its configuration. To start fresh with documents, delete the bot and recreate it with new files.',
        },
        {
          q: 'The page is loading slowly. What can I do?',
          a: 'Try: 1) Clear your browser cache, 2) Check your internet connection, 3) Close unnecessary browser tabs, 4) Ensure you\'re using a modern browser (Chrome, Firefox, Edge).',
        },
      ],
    },
    {
      id: 'account',
      title: 'Account & Settings',
      icon: '',
      questions: [
        {
          q: 'How do I change my account settings?',
          a: 'Click on "Settings" in the sidebar to access your account preferences, profile information, and application settings.',
        },
        {
          q: 'Can I use multiple projects?',
          a: 'Yes! You can create multiple projects to organize your bots and documents. Each project keeps its data separate.',
        },
        {
          q: 'Is my data secure?',
          a: 'Yes, your data is stored locally and securely. We don\'t share your documents or bot configurations with third parties. All processing happens on your machine when using LM Studio.',
        },
        {
          q: 'How do I delete my account?',
          a: 'Account deletion can be done through the Settings page. This will permanently remove all your bots, documents, and data.',
        },
      ],
    },
  ];

  const toggleQuestion = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  const filteredCategories = faqCategories.map((category) => ({
    ...category,
    questions: category.questions.filter(
      (item) =>
        item.q.toLowerCase().includes(searchQuery.toLowerCase()) ||
        item.a.toLowerCase().includes(searchQuery.toLowerCase())
    ),
  })).filter((category) => category.questions.length > 0);

  const allQuestions = faqCategories.flatMap((cat) => cat.questions);
  const hasResults = filteredCategories.length > 0;

  return (
    <div className="help-faq-page">
      <header className="help-faq-header">
        <div className="help-faq-header-content">
          <div className="help-faq-header-badge">Help Center</div>
          <h1>Frequently Asked Questions</h1>
          <p className="help-faq-subtitle">
            Find answers to common questions and learn how to get the most out of Recall AI
          </p>
        </div>
      </header>

      <div className="help-faq-container">
        {/* Search Bar */}
        <div className="help-faq-search">
          <div className="help-faq-search-wrapper">
            <svg
              className="help-faq-search-icon"
              width="20"
              height="20"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
            >
              <circle cx="11" cy="11" r="8"></circle>
              <path d="m21 21-4.35-4.35"></path>
            </svg>
            <input
              type="text"
              placeholder="Search for questions or topics..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="help-faq-search-input"
            />
            {searchQuery && (
              <button
                className="help-faq-search-clear"
                onClick={() => setSearchQuery('')}
                aria-label="Clear search"
              >
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <line x1="18" y1="6" x2="6" y2="18"></line>
                  <line x1="6" y1="6" x2="18" y2="18"></line>
                </svg>
              </button>
            )}
          </div>
          {searchQuery && (
            <div className="help-faq-search-results">
              Found {filteredCategories.reduce((sum, cat) => sum + cat.questions.length, 0)} result(s)
            </div>
          )}
        </div>

        {/* Quick Links */}
        {!searchQuery && (
          <div className="help-faq-quick-links">
            <h3>Quick Links</h3>
            <div className="help-faq-quick-links-grid">
              <a href="#getting-started" className="help-faq-quick-link">
                <span className="help-faq-quick-link-icon"></span>
                <span>Getting Started</span>
              </a>
              <a href="#bot-setup" className="help-faq-quick-link">
                <span className="help-faq-quick-link-icon"></span>
                <span>Bot Setup</span>
              </a>
              <a href="#code-to-doc" className="help-faq-quick-link">
                <span className="help-faq-quick-link-icon"></span>
                <span>Code to Document</span>
              </a>
              <a href="#troubleshooting" className="help-faq-quick-link">
                <span className="help-faq-quick-link-icon"></span>
                <span>Troubleshooting</span>
              </a>
            </div>
          </div>
        )}

        {/* FAQ Categories */}
        <div className="help-faq-content">
          {hasResults ? (
            filteredCategories.map((category) => (
              <section key={category.id} id={category.id} className="help-faq-category">
                <div className="help-faq-category-header">
                  <span className="help-faq-category-icon">{category.icon}</span>
                  <h2>{category.title}</h2>
                </div>
                <div className="help-faq-questions">
                  {category.questions.map((item, index) => {
                    const globalIndex = faqCategories
                      .slice(0, faqCategories.indexOf(category))
                      .reduce((sum, cat) => sum + cat.questions.length, 0) + index;
                    const isOpen = openIndex === globalIndex;

                    return (
                      <div
                        key={index}
                        className={`help-faq-item ${isOpen ? 'open' : ''}`}
                      >
                        <button
                          className="help-faq-question"
                          onClick={() => toggleQuestion(globalIndex)}
                          aria-expanded={isOpen}
                        >
                          <span className="help-faq-question-text">{item.q}</span>
                          <svg
                            className={`help-faq-chevron ${isOpen ? 'open' : ''}`}
                            width="20"
                            height="20"
                            viewBox="0 0 24 24"
                            fill="none"
                            stroke="currentColor"
                            strokeWidth="2"
                          >
                            <polyline points="6 9 12 15 18 9"></polyline>
                          </svg>
                        </button>
                        <div className="help-faq-answer">
                          <div className="help-faq-answer-content">{item.a}</div>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </section>
            ))
          ) : (
            <div className="help-faq-no-results">
              <div className="help-faq-no-results-icon"></div>
              <h3>No results found</h3>
              <p>Try different keywords or browse the categories below</p>
              <button
                className="help-faq-clear-search-btn"
                onClick={() => setSearchQuery('')}
              >
                Clear Search
              </button>
            </div>
          )}
        </div>

        {/* Contact Support */}
        <div className="help-faq-contact">
          <div className="help-faq-contact-content">
            <h3>Still need help?</h3>
            <p>Can't find what you're looking for? Contact our support team</p>
            <button
              className="help-faq-contact-btn"
              onClick={() => {
                // Trigger report modal by clicking the Report menu item
                const reportMenuItems = document.querySelectorAll('.menu-item');
                reportMenuItems.forEach((item) => {
                  const text = item.textContent || item.innerText;
                  if (text.includes('Report')) {
                    item.click();
                  }
                });
              }}
            >
              Contact Support
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default HelpAndFAQPage;

